apiVersion: v1
kind: Service
metadata:
  name: validation-server-loadbalancer
spec:
  selector:
    app: validation-server-loadbalancer
  ports:
    - protocol: TCP
      name: port-name-validation
      port: 8081
  type: LoadBalancer